[build]
  command = "next build"
  publish = ".next"

[dev]
  command = "next dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
